import { Barlow } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "  @/components/theme-provider";
import Header from "./components/Header";

const barlow = Barlow({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-barlow",
  weight: ["500", "600", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${barlow.variable}`} lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
            <Header/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
